// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACsXRblEKdS7hoG7m23orhCl2Blhh1Muc',
    appId: '1:163558543292:web:1ef2eeb134e5f0fea265b9',
    messagingSenderId: '163558543292',
    projectId: 'nuru-app',
    authDomain: 'nuru-app.firebaseapp.com',
    storageBucket: 'nuru-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsLtmX_pd1AfEho7F295ZXtWsxrfPR_ck',
    appId: '1:163558543292:android:79573e21a7c1ffbfa265b9',
    messagingSenderId: '163558543292',
    projectId: 'nuru-app',
    storageBucket: 'nuru-app.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACsXRblEKdS7hoG7m23orhCl2Blhh1Muc',
    appId: '1:163558543292:web:8852619c7cebe426a265b9',
    messagingSenderId: '163558543292',
    projectId: 'nuru-app',
    authDomain: 'nuru-app.firebaseapp.com',
    storageBucket: 'nuru-app.firebasestorage.app',
  );
}
